### PR TITLE
✨  Remove join Discord button when link is null

### PR DESCRIPTION
**Pull request by MisterDeen1694**
Again a rebuild is needed since i again changed some styling this pull will remove the "Join server" button on the discord widget when there is chosen for No Invite in the discord widget settings it also fixes the height of the widget when button is removed

### CODE REVIEW

**Comment by DennisObject** [comment]
I'm not sure if it's me who's misunderstanding the supposed outcome of the fix 😓

But to me it seems like it would never hit your condition to remove the button

`if (data.instant_invite === null || data.instant_invite.length === 0) {
                            console.log("we should remove")
                            document.getElementById('guildInvite').remove()
                            document.getElementById('guildUsers').style.height = "176px"
                        } else {
                            //Gives the "Join server" button an href to the default selected chennel in the server
                            //link is recived from widget json
                            document.getElementById('guildInvite').setAttribute('href', data.instant_invite)
                        }`

As you already have a check in the very beginning, returning if the status !== 200
`if (res.status != 200) {}`

So to from my understanding you can revert your if else statement, and instead move 

`document.getElementById('guildInvite').remove()
 document.getElementById('guildUsers').style.height = "176px"`

To the `if (res.status != 200) {}`

Thank you for the contribution!

**Comment by MisterDeen1694** [comment]
> I'm not sure if it's me who's misunderstanding the supposed outcome of the fix 😓
> 
> But to me it seems like it would never hit your condition to remove the button
> 
> `if (data.instant_invite === null || data.instant_invite.length === 0) { console.log("we should remove") document.getElementById('guildInvite').remove() document.getElementById('guildUsers').style.height = "176px" } else { //Gives the "Join server" button an href to the default selected chennel in the server //link is recived from widget json document.getElementById('guildInvite').setAttribute('href', data.instant_invite) }`
> 
> As you already have a check in the very beginning, returning if the status !== 200 `if (res.status != 200) {}`
> 
> So to from my understanding you can revert your if else statement, and instead move
> 
> `document.getElementById('guildInvite').remove() document.getElementById('guildUsers').style.height = "176px"`
> 
> To the `if (res.status != 200) {}`
> 
> Thank you for the contribution!

Hi I rechecked the code and its correct since the ```res.status``` gives an error when it cant connect to the discord api or cant find the server with the guildID. And the ```data.instant_invite``` is a part of the json file witch defines if there is an invite channel to the server selected in the settings. 
if there is no channel selected it returns ```"instant_invite": null``` and if there is an channel selected it returns ```"instant_invite": "https://discordapp.com/invite/xFqNmcBs"```

Hope that this makes it clear sorry for my bed writing/English

**Comment by DennisObject** [comment]
> > I'm not sure if it's me who's misunderstanding the supposed outcome of the fix 😓
> > But to me it seems like it would never hit your condition to remove the button
> > `if (data.instant_invite === null || data.instant_invite.length === 0) { console.log("we should remove") document.getElementById('guildInvite').remove() document.getElementById('guildUsers').style.height = "176px" } else { //Gives the "Join server" button an href to the default selected chennel in the server //link is recived from widget json document.getElementById('guildInvite').setAttribute('href', data.instant_invite) }`
> > As you already have a check in the very beginning, returning if the status !== 200 `if (res.status != 200) {}`
> > So to from my understanding you can revert your if else statement, and instead move
> > `document.getElementById('guildInvite').remove() document.getElementById('guildUsers').style.height = "176px"`
> > To the `if (res.status != 200) {}`
> > Thank you for the contribution!
> 
> Hi I rechecked the code and its correct since the `res.status` gives an error when it cant connect to the discord api or cant find the server with the guildID. And the `data.instant_invite` is a part of the json file witch defines if there is an invite channel to the server selected in the settings. if there is no channel selected it returns `"instant_invite": null` and if there is an channel selected it returns `"instant_invite": "https://discordapp.com/invite/xFqNmcBs"`
> 
> Hope that this makes it clear sorry for my bed writing/English

Oh okay I see! thanks for clarifying 😄 that makes perfect sense

**Review by DennisObject — APPROVED** [review]
looks good 💪🏻 thank you for the contribution

**Pull request merged**
